# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - prueba-e

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prueba-e'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f18a6aa9f1c54dd39eb34eadb6584874 }}
        package: '${{ github.workspace }}/dist/*.war'
